dist: trusty
sudo: false
language: node_js
node_js:
  - 9

before_install: npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
# Only the node version 6 job will upload the lockfile
after_script: greenkeeper-lockfile-upload

cache:
  directories:
    - "node_modules"
