# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - run:
        name: Install Dependencies
        command: npm i

      - run:
        name: Install Greenkeeper-lockfile
        command: npm i greenkeeper-lockfile@1

      - run:
        name: Update the lockfile
        command: npx greenkeeper-lockfile-update

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}

      - run: npm test

      - run:
        name: Commit lockfile changes
        command: npx greenkeeper-lockfile-upload
